### ISSUE TITLE
[Feat] 출고 요청 거절, 수락 mock 기능

### ISSUE THREAD

**Issue by wjdrltjr5** [8-palbochae/seahere-backend#2]
## 📝 Description
/outgorings/{outgoringId} url reqeustBody로 넘어오는 state에 맞게 변경
```
patch
{
  "state" : pending or reject
}
```

## 📍 Todo
- [x] 요청한 outgoring id 상태를 pending으로 바꾸는 기능
- [x] 요청한 outgoring id 상태를 reject으로 바꾸는 기능

## 📢 To Reviewers
메소드명이 괜찮은지 봐주세요

**Comment by woneveryday** [comment]
괜찮은 거 같아요
